# Generated by Django 5.1.5 on 2025-01-28 15:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg_area', models.CharField(max_length=150)),
                ('kpi', models.CharField(max_length=150)),
                ('kpi_species', models.CharField(max_length=250)),
                ('details', models.TextField()),
                ('performer', models.CharField(max_length=150)),
                ('performer_rating', models.CharField(choices=[('ROT', 'Rot'), ('GELB', 'Gelb'), ('GRÜN', 'Gruen'), ('Undefined', 'Undefined')], max_length=50, null=True)),
                ('recipient', models.CharField(max_length=150)),
                ('recipient_rating', models.CharField(choices=[('ROT', 'Rot'), ('GELB', 'Gelb'), ('GRÜN', 'Gruen'), ('Undefined', 'Undefined')], max_length=50, null=True)),
                ('total_rating', models.CharField(choices=[('ROT', 'Rot'), ('GELB', 'Gelb'), ('GRÜN', 'Gruen'), ('Undefined', 'Undefined')], max_length=50, null=True)),
                ('wp', models.TextField()),
                ('archieving_relevance', models.BooleanField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 56, 22, 43027, tzinfo=datetime.timezone.utc), verbose_name='pub date')),
            ],
        ),
        migrations.CreateModel(
            name='BadRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description_performer', models.CharField(default='None', max_length=200)),
                ('problem_description_recipient', models.CharField(default='None', max_length=200)),
                ('measure', models.CharField(default='None', max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('deadline', models.DateTimeField(default=None, verbose_name='date published')),
                ('work_package', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.workpackage')),
            ],
        ),
    ]
