# Generated by Django 5.1.5 on 2025-01-29 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_workpackage_wp_id_alter_badrating_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badrating',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 15, 48, 59, 388178), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 15, 48, 59, 387799), verbose_name='pub date'),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='rg_area',
            field=models.CharField(choices=[('RG_A', 'Rg A'), ('RG_B', 'Rg B'), ('RG_C', 'Rg C'), ('RG_D', 'Rg D'), ('RG_E', 'Rg E'), ('RG_F', 'Rg F'), ('Undefined', 'Undefined')], max_length=150, null=True),
        ),
    ]
