# Generated by Django 5.1.5 on 2025-01-30 07:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_alter_badrating_deadline_alter_workpackage_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpackage',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='pub date'),
        ),
        migrations.CreateModel(
            name='MeasuresForBadRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description_performer', models.CharField(default='None', max_length=200)),
                ('problem_description_recipient', models.CharField(default='None', max_length=200)),
                ('measure', models.CharField(default='None', max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2025, 1, 30, 8, 54, 18, 370632), verbose_name='date published')),
                ('work_package', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.workpackage')),
            ],
        ),
        migrations.DeleteModel(
            name='BadRating',
        ),
    ]
