# Generated by Django 5.1.5 on 2025-02-06 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_alter_workpackage_pub_date_measuresforbadrating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WP_ID', models.CharField(default='-', max_length=150)),
                ('rg_area', models.CharField(choices=[('RG_A', 'Rg A'), ('RG_B', 'Rg B'), ('RG_C', 'Rg C'), ('RG_D', 'Rg D'), ('RG_E', 'Rg E'), ('RG_F', 'Rg F'), ('Undefined', 'Undefined')], max_length=150, null=True)),
                ('kpi', models.CharField(max_length=150)),
                ('kpi_species', models.CharField(max_length=250)),
                ('details', models.TextField()),
                ('performer', models.CharField(max_length=150)),
                ('performer_rating', models.CharField(choices=[('ROT', 'Rot'), ('GELB', 'Gelb'), ('GRÜN', 'Gruen'), ('Undefined', 'Undefined')], max_length=50, null=True)),
                ('recipient', models.CharField(max_length=150)),
                ('recipient_rating', models.CharField(choices=[('ROT', 'Rot'), ('GELB', 'Gelb'), ('GRÜN', 'Gruen'), ('Undefined', 'Undefined')], max_length=50, null=True)),
                ('total_rating', models.CharField(choices=[('ROT', 'Rot'), ('GELB', 'Gelb'), ('GRÜN', 'Gruen'), ('Undefined', 'Undefined')], max_length=50, null=True)),
                ('wp', models.TextField()),
                ('archieving_relevance', models.BooleanField()),
                ('pub_date', models.DateField(default=datetime.datetime.now, verbose_name='pub date')),
            ],
        ),
        migrations.AlterField(
            model_name='measuresforbadrating',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 14, 16, 44, 557782), verbose_name='date published'),
        ),
    ]
