# Generated by Django 5.1.5 on 2025-02-06 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_testpackages_alter_measuresforbadrating_deadline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestPackages',
            new_name='TestPackage',
        ),
        migrations.AlterField(
            model_name='measuresforbadrating',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 14, 21, 4, 108660), verbose_name='date published'),
        ),
    ]
