# Generated by Django 5.1.5 on 2025-02-10 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_rename_testpackages_testpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackage',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='measuresforbadrating',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 10, 15, 49, 39, 702483), verbose_name='date published'),
        ),
    ]
