# Generated by Django 5.1.5 on 2025-02-10 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_workpackage_file_workpackage_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpackage',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='testpackage',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='measuresforbadrating',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 10, 16, 0, 47, 84335), verbose_name='date published'),
        ),
    ]
