# Generated by Django 5.1.5 on 2025-02-10 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_testpackage_file_testpackage_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuresforbadrating',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 10, 16, 4, 1, 597445), verbose_name='date published'),
        ),
    ]
