# Generated by Django 5.1.5 on 2025-03-20 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_alter_measuresforbadrating_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workpackage',
            name='total_rating',
        ),
        migrations.AlterField(
            model_name='measuresforbadrating',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 14, 10, 17, 515511), verbose_name='date published'),
        ),
    ]
