# Generated by Django 5.1.5 on 2025-03-21 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_remove_workpackage_total_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuresforbadrating',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 13, 31, 10, 915582), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='performer',
            field=models.CharField(choices=[('Vehicle Security Architect', 'Vehicle Security Architect'), ('CarIT Carline Coordinator', 'Carit Carline Coordinator'), ('CarIT Risk Manager', 'Carit Risk Manager'), ('Procurement MP', 'Procurement Mp'), ('CarIT Supplier Manager', 'Carit Supplier Manager'), ('Security Architect', 'Security Architect'), ('CarIT Governance Coordinator', 'Carit Governance Coordinator'), ('E2', 'E2'), ('PL Carline', 'Pl Carline'), ('Vehicle Pentest Coordinator', 'Vehicle Pentest Coordinator'), ('BTV', 'Btv'), ('CarIT Security Manadate', 'Carit Security Mandate'), ('Supplier', 'Supplier'), ('N/A', 'Not Defined')], max_length=150),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='recipient',
            field=models.CharField(choices=[('Vehicle Security Architect', 'Vehicle Security Architect'), ('CarIT Carline Coordinator', 'Carit Carline Coordinator'), ('CarIT Risk Manager', 'Carit Risk Manager'), ('Procurement MP', 'Procurement Mp'), ('CarIT Supplier Manager', 'Carit Supplier Manager'), ('Security Architect', 'Security Architect'), ('CarIT Governance Coordinator', 'Carit Governance Coordinator'), ('E2', 'E2'), ('PL Carline', 'Pl Carline'), ('Vehicle Pentest Coordinator', 'Vehicle Pentest Coordinator'), ('BTV', 'Btv'), ('CarIT Security Manadate', 'Carit Security Mandate'), ('Supplier', 'Supplier'), ('N/A', 'Not Defined')], max_length=150),
        ),
    ]
