# Generated by Django 5.1.5 on 2025-03-28 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_alter_measuresforbadrating_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpackage',
            name='id',
        ),
        migrations.AlterField(
            model_name='measuresforbadrating',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 21, 39, 39, 789081), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='WP_ID',
            field=models.CharField(default='-', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='performer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='recipient',
            field=models.CharField(max_length=150),
        ),
    ]
