# Generated by Django 5.1.5 on 2025-03-31 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_remove_testpackage_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestPackage',
        ),
        migrations.AlterField(
            model_name='measuresforbadrating',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 10, 24, 35, 199966), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='rg_area',
            field=models.CharField(choices=[('ML-A', 'Rg A'), ('ML-B', 'Rg B'), ('ML-C', 'Rg C'), ('ML-D', 'Rg D'), ('ML-E', 'Rg E'), ('ML-F', 'Rg F'), ('Undefined', 'Undefined')], max_length=150, null=True),
        ),
    ]
