# Generated by Django 5.1.5 on 2025-03-31 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0017_delete_testpackage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WP_ID', models.CharField(default='-', max_length=150)),
                ('rg_area', models.CharField(choices=[('RG_A', 'Rg A'), ('RG_B', 'Rg B'), ('RG_C', 'Rg C'), ('RG_D', 'Rg D'), ('RG_E', 'Rg E'), ('RG_F', 'Rg F'), ('Undefined', 'Undefined')], max_length=150, null=True)),
                ('kpi', models.CharField(max_length=150)),
                ('kpi_species', models.CharField(max_length=250)),
                ('details', models.TextField()),
                ('performer', models.CharField(max_length=150)),
                ('performer_rating', models.CharField(choices=[('ROT', 'Rot'), ('GELB', 'Gelb'), ('GRÜN', 'Gruen'), ('Undefined', 'Undefined')], max_length=50, null=True)),
                ('recipient', models.CharField(max_length=150)),
                ('recipient_rating', models.CharField(choices=[('ROT', 'Rot'), ('GELB', 'Gelb'), ('GRÜN', 'Gruen'), ('Undefined', 'Undefined')], max_length=50, null=True)),
                ('total_rating', models.CharField(choices=[('ROT', 'Rot'), ('GELB', 'Gelb'), ('GRÜN', 'Gruen'), ('Undefined', 'Undefined')], max_length=50, null=True)),
                ('wp', models.TextField()),
                ('link', models.URLField(null=True)),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('archieving_relevance', models.BooleanField()),
                ('pub_date', models.DateField(default=datetime.datetime.now, verbose_name='pub date')),
            ],
        ),
        migrations.AlterField(
            model_name='measuresforbadrating',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 10, 25, 35, 503261), verbose_name='date published'),
        ),
    ]
