# Generated by Django 5.1.5 on 2025-03-31 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0018_testpackage_alter_measuresforbadrating_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuresforbadrating',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 10, 26, 17, 360485), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='WP_ID',
            field=models.CharField(max_length=150),
        ),
    ]
