# Generated by Django 5.1.5 on 2025-04-04 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0019_alter_measuresforbadrating_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuresforbadrating',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 4, 13, 47, 59, 756164), verbose_name='date published'),
        ),
    ]
